# Generated by Django 4.0.3 on 2022-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0023_image_field_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionality',
            options={'verbose_name': 'funcionalidad', 'verbose_name_plural': 'funcionalidades'},
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='doggieHommie.user'),
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='bank_name',
            field=models.CharField(choices=[('Nequi', 'Nequi'), ('Paypal', 'Paypal'), ('Daviplata', 'Daviplata')], max_length=120),
        ),
    ]
