# Generated by Django 4.0.3 on 2022-05-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0024_alter_functionality_options_post_likes_and_more'),
    ]

    operations = [
    
        migrations.RemoveField(
            model_name='post',
            name='likes'
        )
    ]
