# Generated by Django 4.0.3 on 2022-05-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0025_postsliked_alter_post_likes_postsliked_post_and_more'),
    ]

    operations = [
        
    ]
