# Generated by Django 4.0.3 on 2022-05-31 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0026_remove_post_likes_delete_postsliked'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', through='doggieHommie.PostsLiked', to='doggieHommie.user'),
        ),
        migrations.AddField(
            model_name='postsliked',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.post'),
        ),
        migrations.AddField(
            model_name='postsliked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggieHommie.user'),
        ),
    ]
