# Generated by Django 4.0.3 on 2022-06-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggieHommie', '0026_remove_post_likes_delete_postsliked'),
        ('doggieHommie', '0027_postsliked_alter_functionality_options_post_likes_and_more'),
    ]

    operations = [
    ]
